-- sql comment
CREATE DATABASE IF NOT EXISTS mini_shop_class
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;
USE mini_shop_class;

-- USERS: customers + admin
CREATE TABLE users (
    id  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    email   VARCHAR(191) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role    ENUM('user', 'admin') NOT NULL DEFAULT 'user',
    is_active   TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;

-- Categories 
CREATE TABLE Categories (
    id  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(120) NOT NULL,
    slug    VARCHAR(160) NOT NULL UNIQUE,
    description TEXT NULL,
    is_active   TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;


-- Products
CREATE TABLE products (
    id  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(120) NOT NULL,
    slug    VARCHAR(160) NOT NULL UNIQUE,
    description TEXT NULL,
    price   DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    stock   INT UNSIGNED NOT NULL DEFAULT 0,
    image   VARCHAR(255) NULL, 
    is_active   TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB;

-- multiple images